[project]
name = "grag-indexer-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "neo4j>=5.28.1",
    "pymilvus>=2.5.6",
    "python-dotenv>=1.1.0",
    "sentence-transformers>=4.0.1",
]
