[project]
name = "grag-indexer-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymilvus>=2.5.6",
    "sentence-transformers>=4.0.1",
]
